-- MySQL Script generated by MySQL Workbench
-- 03/14/15 23:04:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_CASAHERRERO
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `DB_CASAHERRERO` ;

-- -----------------------------------------------------
-- Schema DB_CASAHERRERO
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_CASAHERRERO` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `DB_CASAHERRERO` ;

-- -----------------------------------------------------
-- Table `G6_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G6_Curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `G6_Curso` (
  `idCurso` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `estado` INT(1) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `G6_Ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G6_Ciclo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `G6_Ciclo` (
  `idCiclo` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(2) NULL,
  `estado` INT(1) NULL,
  PRIMARY KEY (`idCiclo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `G6_PlanCurricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G6_PlanCurricular` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `G6_PlanCurricular` (
  `idPlanCurricular` VARCHAR(10) NOT NULL,
  `anio` VARCHAR(4) NULL,
  `semestre` VARCHAR(1) NULL,
  `cantCredito` INT(1) NULL,
  `cantHoraTeoria` INT(1) NULL,
  `cantHoraLaboratorio` INT(1) NULL,
  `idCurso` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idPlanCurricular`, `idCurso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `G6_PreRequisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G6_PreRequisito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `G6_PreRequisito` (
  `idPreRequisito` VARCHAR(10) NOT NULL,
  `idPlanCurricular` VARCHAR(10) NOT NULL,
  `idCursoPre` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idPreRequisito`, `idPlanCurricular`, `idCursoPre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `G6_PlanCurricular_Ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `G6_PlanCurricular_Ciclo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `G6_PlanCurricular_Ciclo` (
  `idPlanCurricular` VARCHAR(10) NOT NULL,
  `idCurso` VARCHAR(6) NOT NULL,
  `idCiclo` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idPlanCurricular`, `idCurso`, `idCiclo`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
